### ISSUE TITLE
Change wording of comment

### ISSUE THREAD

**Issue by Conmy** [dxcore35/obs-Calendar#1]
https://github.com/dxcore35/obs-Calendar/blob/68615bca4130707d2bd96e44937ea99158a034ee/obs-insert_calendar.py#L13

Hey. On this line above, the comment mentioned the format has to be in `regex` but I don't think this counts as standard regex notation.
Maybe instead reference this list from the python docs to find the correct formatting codes.
https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

**Comment by dxcore35** [comment]
You are right, it is mixture of regex with strf time formatting.
I changed the comment to be it more helpful. Thank you!
